# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytHzZzW5Rs91avEU8I-knBfk8fS0fe4t
"""

#3

input3= open("/content/sample_data/input3.txt","r")
output3= open("/content/sample_data/output3.txt","w")
input3.readline()
a=input3.readline()
a_rr =a.split()
def bblsort(a_rr):
  b=0
  for x in range(len(a_rr)-2):
    if int(a_rr[x+1])<int(a_rr[x]):
      b=1
      break

  if b==1:
    for y in range(len(a_rr)-1):
      for z in range(len(a_rr)-y-1):
        if int(a_rr[z]) > int(a_rr[z+1]):
          a_rr[z],a_rr[z+1]=a_rr[z+1],a_rr[z]
    else:
      print("Sorting not required",file= output3)
    return a_rr
  n = bblsort(a_rr)
  for m in range(len(a_rr)):
    print(int(n[m]),end=" ", file=output3)