# -*- coding: utf-8 -*-
"""LabAssignmentNo-02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1elNpnlaJQrTrOh4cEt9xGtmMPlVOdDK9
"""

inp=open("/content/drive/MyDrive/cse221-lab2/input01.txt","r")
outp=open("/content/drive/MyDrive/cse221-lab2/output01.txt","w")

arr=int(inp.readline())
ip=inp.readline().split(" ")
py=inp.readline().split(" ")
ip1=[]
py1=[]
for a in range(arr):
  ip1.append(int(ip[a]))
for a in range(arr):
  py1.append(int(py[a]))

for a1 in range(1,len(py1)):
  tem=py1[a1]
  tem1=ip1[a1]
  a2=a1-1
  while a2>=0:
    if tem>py1[a2]:
      py1[a2+1]=py1[a2]
      ip1[a2+1]=ip1[a2]
      a2-=1
    else:
      break
  py1[a2+1]=tem
  ip1[a2+1]=tem1
for a3 in range(len(ip1)):
  print(ip1[a3],end=" ",file=outp)

def mrg(w,x,y):
  a1=len(w)
  a2=len(x)
  a,b,c=0,0,0

  while a<a1 and b<a2:
    if w[a]<=x[b]:
      y[c]=w[a]
      c+=1
      b+=1
    else:
      y[c]=x[b]
      c+=1
      b+=1
  while a<a1:
    y[c]=w[a]
    a+=1
    c+=1
  while b<a2:
    y[c]=x[b]
    b+=1
    c+=1

def MrgSrt(y):
  i=len(y)
  if i<2:
    return
  else:
    m=i//2
    import math
    l=[]
    r=[]
    for x in range(0,m):
      l.append(y[x])
    for x in range(m,i):
      r.append(y[x])

    MrgSrt(l)
    MrgSrt(r)
    mrg(l,r,y)


fi=open('/content/drive/MyDrive/cse221-lab2/input02.txt','r')
fd=open("/content/drive/MyDrive/cse221-lab2/output02.txt",'w')
aa=int(fi.readline())
ar=fi.readline().split(' ')   
arr1=[]
for e in ar:
  arr1.append(int(e))
MrgSrt(arr1)
for e in range(aa):
  print(arr1[e],end=' ',file=fd)

def Qsort(a,s,e):
  if s>=e:
    return
  elif s<e:
    piv=prttion(a,s,e)
    Qsort(a,s,piv-1)
    Qsort(a,piv+1,e)
    
def prttion(a,s,e):
  p=a[e]
  prt_idx=s

  for x in range(s,e):
    if a[x]<=p:
      a[x],a[prt_idx]=a[prt_idx],a[x]
      prt_idx+=1
  a[prt_idx],a[e]=a[e],a[prt_idx]
  return prt_idx


i=open('/content/drive/MyDrive/cse221-lab2/input03-a.txt','r')
o=open('/content/drive/MyDrive/cse221-lab2/output03-a.txt','w')
#x=int(i.readline())
ar=i.readline().split(' ')
ar1=[]

for l in ar:
  ar1.append(int(l))

Qsort(ar1,0,len(ar1)-1)

for j in range(len(ar1)):
  print(ar1[j],end=' ',file=o)



############################# 3-b ###################################

inn=open('/content/drive/MyDrive/cse221-lab2/input03-b.txt','r')
outt=open('/content/drive/MyDrive/cse221-lab2/output03-b.txt','w')

def findk(a,x,y,z):
  if y==z:
    return a[y]
  pq=prttion(a,y,x)
  qp=pq-y+1

  if x==qp:
    return a[pq]
  if x>qp :
    return findk(a,x,y,pq-1)
  else:
    return findk(a,x-qp,pq+1,z)

xx=[]
for x in inn:
  xx.append(x)

ar1= xx[0].split(" ")
ar1=ar1[2:len(ar1)]
ar1[len(ar1)-1]=ar1[len(ar1)-1][0:len(ar1[len(ar1)-1])-1]

for a in range(len(ar1)):
  ar1[a]=int(ar1[a])

xx=xx[1:len(xx)]
k=[]
for a in xx:
  pnt=a[0:len(a)].split(" ")
  k.append(int(pnt[a]))

for j in k:
  print(findk(ar1,x,0,len(ar1)-1),file=inn)

def bsort(xx,yy):

  ln=len(xx)
  for a in range(ln):
    for b in range(0,ln-a-1):
      if xx[b]>xx[b+1]:
        xx[b], xx[j+1] = xx[b+1], xx[b]
        yy[b], yy[j+1] = yy[b+1], yy[j]

inp4=open('/content/drive/MyDrive/cse221-lab2/input04-1.txt','r')
out4=open('/content/drive/MyDrive/cse221-lab2/output04-1.txt','w')

def enq(xx,yy,x,y):
  xx.append(x)
  yy.append(y)
  bsort(xx,yy)
def seedoc(yy,xx):
  print(yy[0])

def prntQ(ar1):
  print(yy)

i=[]
for a in inp4:
  i.append(i)

xx=[]
yy=[]

for a in i:
  if 'see doctor' in a:
    seedoc(xx,yy)
    yy=yy[1:]
    xx=xx[1:]
  else:
    t=a.split(' ')
    y=t[0]
    x=int(t[1])
    enq(xx,yy,x,y)
print(yy,"NQ",file=out4)
print(xx,'xQ',file=out4)

