# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NN4LXk4Hj7kzYkRh2q-GyxyWc17NCkBk
"""

#3 -- DFS

def bGuloD(c_c, in3):
  g = {}
  count= 0
  while (count<c_c):
    L = in3.readline()

    x,y = L.split(" ")
    y = y.strip()
    x=int(x)
    y=int(y)

    if(x not in g):
      g[x] = [x]

    else:
      g[x].append(y)

    if(y in g):
      g[y].append(x)

    else:
      g[y]= [x]
    count+=1
  return g

def DFS (g, h,discovered,out3):
  discovered[h]= "discovered"
  print(h, end=" ",file=out3)
  if h in g.keys():
    for eg in g[h]:
      if discovered[eg]==0:
        DFS(g, eg, discovered,out3)

in3 = open("/content/drive/MyDrive/Lab04/in3.txt","r")
out3 = open("/content/drive/MyDrive/Lab04/out3.txt","w")

line= in3.readline()

line=line.strip()
line=line.split(" ")
n_n=int (line[0])
c_c=int(line[1])

gph=bGuloD(c_c,in3)

DFS(gph,1,[0]*(n_n+1),out3)