# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167aDpjkmMqUomgBqD0_-SiFghnPMPrRY
"""

#4
BFS

inp4=open("/content/drive/MyDrive/Lab05/input05-4.txt","r")
outp4=open("/content/drive/MyDrive/Lab05/output05-4.txt","w")