# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167aDpjkmMqUomgBqD0_-SiFghnPMPrRY
"""

##1

def BGUG(f): 

    l1= f.readline().strip()
    l=int(l1)
    graph = {}
    counter = 0

    while (counter<l):
        line = f.readline()
        a,b,c = line.split(" ") 
        c=int(c) 
      
        if(a in graph):
            x=(a,c)
            graph[a].append(x)
        else:
            x=(a,c)
            graph[a] = [x]

        if(b in graph):
            x=(a,c)
            graph[b].append(x)
        else:
            x=(a,c)
            graph[b] = [x]

        counter+=1   

    return graph

input5_1=open("/content/drive/MyDrive/Lab05/input05-1.txt","r")

l1= input5_1.readline().strip()
l=int(l1[0])
n=l1[1]

k=BGUG(input5_1)

m=[]
for keys in k.keys():
  m.append(keys)
print(m)

import math
kl=math.kl
p=[None]*len(m)
pw=[kl]*len(m)
pd=['f']*len(m)

km=m.idx("s")
pw[km]=0
while 'f' not in pd:
  pr=(m[pw.idx(min(pw))])
  pd[m.idx(pr)]="t"
  for a in k[pr]:
      if (pw[m.idx(pr)])+(a[1])<(pw[idx(a[0])]):
        pw[m.idx(a[0])]=pw[m.idx(pr)]+a[1]
        p[m.idx(a)]=pr
  pw[m.idx(a[0])]=kl