# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167aDpjkmMqUomgBqD0_-SiFghnPMPrRY
"""

inp3=open("/content/drive/MyDrive/lab06/inp3.txt","r")
x=inp3.readline()
y=inp3.readline().strip().split(" ")
z=inp3.readline()
y.sort(reverse=True)
a=[] 
b=[]
c=[]
mtr=""
for i in z:
  if i=="J":
    if len(y)>0:
      a.append(y[len(y)-1]) 
      mtr+ str(y[len(y)-1])
      b.append(y[len(y)-1])
      y.pop()
  elif i=="j":
    c.append(b[len(b)-1]) 
    mtr+str((b[len(b)-1]))
    b.pop()
k=0
for m in a:
  k+=int(m)
l=0
for n in c:
  l+=int(n)
mtr+=f"\nJack will work for {str(k)} hours \nJill will work for {str(l)} hours"
outp3=open("/content/drive/MyDrive/lab06/outp3.txt", "w")
print(mtr,file=outp3)