# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167aDpjkmMqUomgBqD0_-SiFghnPMPrRY
"""

rng=100
def squreNumber(rng): 
  q=rng**(1/2)
  p=str(q).split(".")
  if int(p[1])== 0 :
    return True
  else:
    return False
inp4=open("/content/drive/MyDrive/lab06/inp4.txt","r")
abc=""
flag=True
while flag==True:
  mq,nq=inp4.readline().strip().split(" ")
  mq=int(mq)
  nq=int(nq)
  if mq==0 and nq==0: 
    flag=False
  else:
    c=0
    for mn in range(mq,nq+1):
      if squreNumber(mn)==True:
        c+=1
    abc+=str(c)
    abc+="\n"
    c=0 
outp4=open("/content/drive/MyDrive/lab06/outp4.txt","w")
print(abc,file=outp4)