# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167aDpjkmMqUomgBqD0_-SiFghnPMPrRY
"""

inp2=open("/content/drive/MyDrive/lab06/inp2.txt","r")
line1=inp2.readline().strip().split(" ")
xi=int(line1[0])
ix=int(line1[1])
a=[]
b=[]
for i in range(xi):
  x,y= inp2.readline().strip(" ").split()
  a.append(int(x))
  b.append(int(y))
n=len(b)
for i in range(n):
  for j in range(n-i-1):
    if a[j]>a[j+1]:
      b[j],b[j+1]= b[j+1],b[j]
      a[j],a[j+1]= a[j+1],a[j]
a1=[]
b1=[]
c=[]
for i in range(ix):
  b1.append([])
  a1.append([])
  c.append([0])
counter=0
for m in range(len(a)):
  for n in range(len(c)):
    if a[m]>=c[n][0]:
      a1[0].append(a[m])
      b1[0].append(b[m])
      c[n][0]=b[m]
      counter+=1
      break
outp2=open("/content/drive/MyDrive/lab06/outp2.txt","w")
print(counter,file=outp2)