# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167aDpjkmMqUomgBqD0_-SiFghnPMPrRY
"""

inp1=open("/content/drive/MyDrive/lab06/inp1.txt","r")
lines=inp1.readline().strip()
lines=int(lines)
a=[]
b=[]
for i in range(lines):
  x,y=inp1.readline().strip().split(" ")
  a.append(int(x))
  b.append(int(y))
n=len(b)
for i in range(n):
  for j in range(n-i-1):
    if b[j]>b[j+1]:
      b[j],b[j+1]= b[j+1],b[j]
      a[j],a[j+1]= a[j+1],a[j]
lst=[]
lst2=[]
lst.append(a[0])
lst2.append(b[0])
c=b[0]
for i in range(1,n):
  if a[i]>c:
    lst.append(a[i])
    lst2.append(b[i])
    c=b[i]
k=""
k+=str(len(lst))
k+=("\n")
for i in range(len(lst)):
  st=str(lst[i])
  k+=" "
  st=str(lst2[i])
  k+="\n"
out1=open("/content/drive/MyDrive/lab06/outp1.txt","w")
print(k,file=out1)