# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytHzZzW5Rs91avEU8I-knBfk8fS0fe4t
"""

#1a

file =open('/content/sample_data/input1a.txt','r')
output=open('/content/sample_data/output1a.txt','w')

i= file.readline()
iint=int(i)
for x in range(iint):
  j=int(file.readline())
  if j%2==0:
    print(j,'is even',file =output)
  else:
    print(j,'is odd', file =output)

#1b
input1b =open('/content/sample_data/input1b.txt','r')
output1b=open('/content/sample_data/output1b.txt','w')

k=int(input1b.readline())
for i in range(k):
  i=input1b.readline()
  n=i.split()
  b1=int(n[1])
  ak=n[2]
  b2=int(n[3])
  if ak=='+':
    print('The result of',b1,ak,b2,'is',b1+b2,file = output1b)
  elif ak=='-':
    print('The result of',b1,ak,b2,'is',b1-b2,file = output1b)
  elif ak=='*':
    print('The result of',b1,ak,b2,'is',b1*b2,file = output1b)
  elif ak=='/':
    print('The result of',b1,ak,b2,'is',b1/b2,file = output1b)